### ISSUE TITLE
[UI] Implement Cross-chain activity endpoints

### ISSUE THREAD

**Issue by SamantaCasal** [XLabs/wormscan-ui#110]
Aca van un par de ejemplos de calls:
Actividad por volumen: https://api.staging.wormscan.io/api/v1/x-chain-activity?start_time=20230101T000000Z&by=notional
Actividad por numero de transacciones: https://api.staging.wormscan.io/api/v1/x-chain-activity?start_time=20230101T000000Z&by=tx

**Comment by SamantaCasal** [comment]
FYI: @valentinoConti 
1. In mobile, the destination chains do not have the %.
2. Is the design of the bottom sheet applied with the details as shown in https://www.figma.com/file/kVuUyVjFFcRP55xHxHoKtH/WormScan?type=design&node-id=1855-24097&t=QPdLlvHUaqRIWW5h-0 ?
According to what I talked to @Gpluv  about, this is the final design.
Evidence: 
https://github.com/XLabs/wormscan-ui/assets/69044575/e709e88c-3ad4-4f52-aa82-eec8bdc0b1fc


https://github.com/XLabs/wormscan-ui/assets/69044575/a8f3d09a-5619-4f33-ad03-9efd721f4e5d

**Comment by valentinoConti** [comment]
> In mobile, the destination chains do not have the %.

Fixed ✅

> The elements of the chains, percentages, and volume/transactions are not aligned(1) and some are off the chart (2) and (3)

Fixed ✅ 

> Is the design of the bottom sheet applied with the details..?

This will be tackled on another task, I just created the draft task on the Project 👍🏼

**Comment by SamantaCasal** [comment]
The previous points are OK!

**I leave some bugs not mentioned above:**
1. There should be more separation between the destination chains. Please see at https://www.figma.com/file/kVuUyVjFFcRP55xHxHoKtH/WormholeScan?type=design&node-id=0-1&t=XXstG6wbUKlT7nDV-0
2. Destination Chains should not be in bold
3. The percentages are located below each chain. Please see at https://www.figma.com/file/kVuUyVjFFcRP55xHxHoKtH/WormholeScan?type=design&node-id=2912-28242&t=XXstG6wbUKlT7nDV-0
4. Do not take into account since when making the modification of 3 it would be solved.
5. Percentages must be in bold
6. The blue bars next to the destination chains will be "grayed out" when not selected. See at https://www.figma.com/file/kVuUyVjFFcRP55xHxHoKtH/WormholeScan?type=design&node-id=2912-28242&t=XXstG6wbUKlT7nDV-0
7. There must be a margin between the sidebars and the names of the destination chains

Evidence: 


![Image](https://github.com/XLabs/wormscan-ui/assets/69044575/4b7370c4-27e7-4936-9a6f-c03b6a35f08c)

**Comment by valentinoConti** [comment]
> 1. There should be more separation between the destination chains.
> 2. Destination Chains should not be in bold
> 6. The blue bars next to the destination chains will be "grayed out" when not selected.
> 7. There must be a margin between the sidebars and the names of the destination chains.

Fixed those ✅ 👌🏼!

---

For this ones:
> 3. The percentages are located below each chain.
> 4. Do not take into account since when making the modification of 3 it would be solved.
> 5. Percentages must be in bold

I think you are looking at the previous mobile version (Figma screenshot):
![mob bef](https://github.com/XLabs/wormscan-ui/assets/41705567/b5bf5234-4608-4112-af0f-b6ab7ff3b1e8)

and not the one that (if I'm not wrong) is the latest one, the one on the bottom sheet section (Figma screenshot):
![mob aft](https://github.com/XLabs/wormscan-ui/assets/41705567/203a1c13-c570-4cf5-a3b7-2f57603cf0a4)

**Comment by SamantaCasal** [comment]
You're right, it was my mistake! Please disregard those points. The following remain in force:
1. There should be more separation between the destination chains. Please see at https://www.figma.com/file/kVuUyVjFFcRP55xHxHoKtH/WormholeScan?type=design&node-id=0-1&t=XXstG6wbUKlT7nDV-0
2. Destination Chains should not be in bold
3. The blue bars next to the destination chains will be "grayed out" when not selected. See at https://www.figma.com/file/kVuUyVjFFcRP55xHxHoKtH/WormholeScan?type=design&node-id=2912-28242&t=XXstG6wbUKlT7nDV-0
4. There must be a margin between the sidebars and the names of the destination chains
5. The name of the Chain and separator is overlapping

**Evidence:**
![IMG_CA6249A7D1EC-1](https://github.com/XLabs/wormscan-ui/assets/69044575/1579125a-aada-4df8-9cc6-9d96317de7e2)


Thank you very much and sorry for the confusion.

**Comment by SamantaCasal** [comment]
✅  QA OK! 

![Image](https://github.com/XLabs/wormscan-ui/assets/69044575/ebfa9c2c-7120-4d4d-b175-491b2ea48ca7)

✔  For <410px the " | " separator is hidden.

![Image](https://github.com/XLabs/wormscan-ui/assets/69044575/641b0dce-c51d-41e3-901e-750ccf3abdd4)
