### ISSUE TITLE
Mainnet/testnet toggle

### ISSUE THREAD

**Issue by hernandiegosavio** [XLabs/wormscan-ui#115]
**User Story**
As a blockchain developer, I want to be able to change my UI and navigation on the explorer from mainnet to testnet and vice versa so that I can verify my transactions on testnet.

**Acceptance Criteria**

- URL front end address must indicate a difference that user is navigating in testnet (ADDRESS FOR TESTNET: _________)
- Explorer home page must include a new button to toggle testnet or mainnet, requires design
- Full functionality must be retained when switching to testnet
- All testnet transactions must be visible only when toggling testnet and all mainnet transactions must be visible only when mainnet is selected
- Default selection of toggle when user lands on homepage is mainnet
- Do not cache selection (for users that close and return back to the page)

**Assets**
Figma - 

**Additional Notes**

**Comment by SamantaCasal** [comment]
✅ OK ->URL front end address must indicate a difference that user is navigating in testnet (ADDRESS FOR TESTNET: _________)
Evidence:
![Image](https://github.com/XLabs/wormscan-ui/assets/69044575/76c403b8-b662-47af-aea4-f50fa84f711a)

✅ OK -> Default selection of toggle when user lands on homepage is mainnet
✅  OK -> Do not cache selection (for users that close and return back to the page)
✅ Full functionality must be retained when switching to testnet
✅  All testnet transactions must be visible only when toggling testnet and all mainnet transactions must be visible only when mainnet is selected

❗Fail ->  Explorer home page must include a new button to toggle testnet or mainnet, requires design

The background color of the dropdown should be #FFFFFF according to the layout at https://www.figma.com/file/kVuUyVjFFcRP55xHxHoKtH/WormholeScan?node-id=3343%3A30763&mode=dev.
However, it shows up in --color-white-03: #ffffff07 all the time.
Evidence:
![Image](https://github.com/XLabs/wormscan-ui/assets/69044575/d4fc00f3-6fb3-4778-a999-be089cc597e6)

Design
![Image](https://github.com/XLabs/wormscan-ui/assets/69044575/0efd4297-e998-4ab3-af73-2b1c22243510)

FYI: @raop155

**Comment by raop155** [comment]
@SamantaCasal  I used the same component as shown here:

![image](https://github.com/XLabs/wormscan-ui/assets/25652943/1d12c61f-372d-4433-b122-0f18817bce6f)

@Gpluv  can you confirm if this is correct or as Sami says this is should be different (color-wise) ?

Thanks! :)

**Comment by Gpluv** [comment]
**Criterio de aceptación:** 
En cuanto a color: su estado default tiene la propiedad de blanco 3% ... su estado activo/seleccionado: blanco 5%, esto se debería dar en todos los botones. 

Ahora bien, debido a que necesitamos mostrarle y recordarle al usuario cuándo está en Testnet, la idea aquí es que solo en ese momento el botón que como activo con la propieda de blanco 10%. 
Cuando el usuario pase a Mainnet y no tiene seleccionado el botón, pondríamos la propiedad por default.

**Comment by SamantaCasal** [comment]
QA OK! 

![Image](https://github.com/XLabs/wormscan-ui/assets/69044575/7ad429bc-e947-4682-8ab3-b2e0fbcfb7fa)
![Image](https://github.com/XLabs/wormscan-ui/assets/69044575/70948bd4-abf6-4f72-84f9-48183173809d)
