### ISSUE TITLE
[UI] Implement Bottom Sheet for mobile for Sankey Chart

### ISSUE THREAD

**Issue by hernandiegosavio** [XLabs/wormscan-ui#117]

**Comment by SamantaCasal** [comment]
@mliu-xlabs @gabzim @erikXLXYZ  could you help me with the acceptance criteria for this feature?I have the following doubts about it:

1 Should it be seen all the time or only when clicking?

2 When should it close?
2.1 When clicking outside the bottom sheet
2.2 When scrolling
2.3 When clicking inside the bottom sheet

3 Do you think the size is correct? It is wider than the Sankey chart, but that's how I see it in the design ➡ https://www.figma.com/file/kVuUyVjFFcRP55xHxHoKtH/WormholeScan?node-id=3206%3A27945&mode=dev

I leave you a video so you can see how it looks now on an iPhone 11


https://github.com/XLabs/wormscan-ui/assets/69044575/bb6e885d-502b-42e1-b1e8-8dc18e79ceab



FYI: @valentinoConti @Gpluv

**Comment by erikXLXYZ** [comment]
@SamantaCasal 
1 Should it be seen all the time or only when clicking? Only when clicking (tapping)

2 When should it close? When the user uses the slider to close it by sliding down.
2.1 When clicking outside the bottom sheet - Also in this case it should close.
2.2 When scrolling
2.3 When clicking inside the bottom sheet

3 Do you think the size is correct? It is wider than the Sankey chart, but that's how I see it in the design
The size is fine, it should be as wide as the full page.

**Comment by valentinoConti** [comment]
Changes implemented, to see the changes with details, see here: #154

**Comment by SamantaCasal** [comment]
QA OK!
