### ISSUE TITLE
[QA] Transaction Page: Three visual bugs

### ISSUE THREAD

**Issue by SamantaCasal** [XLabs/wormscan-ui#121]
**Environment:**
MacBook Pro, macOS Ventura 13.1.1, Chrome Version 113.0.5672.63.
**Prerequisites:**

**Steps**

1. Go to https://front.staging.wormscan.io/#/
2. Click on Txs
3. Observe the table

**Obtained result:**
1. The title says "Transactions"
2. Elements in the first row should not be in bold
4. The `status` check icons are not aligned

**Expected result:**
1. According to https://www.figma.com/file/kVuUyVjFFcRP55xHxHoKtH/WormholeScan?type=design&node-id=0-1&t=tPbo9T4gv7U9n7Sj-0 it should say Transfers

**Evidence:**
![Screenshot 2023-06-15 at 2 24 47 PM](https://github.com/XLabs/wormscan-ui/assets/69044575/d979a9b8-1eaa-48a6-8db7-eb6dbe0a5b37)

**Comment by raop155** [comment]
> The status check icons are not aligned.

@SamantaCasal  The text length is different between COMPLETED and ONGOING, so this is "not viable", or we cant to force that?
@Gpluv 

On the other hand. "COMPLETED" / "ONGOING" has a `checkmark` sign, this need to be diff right?

**Comment by SamantaCasal** [comment]
These bugs are still valid.
FYI: @Gpluv @raop155

**Comment by SamantaCasal** [comment]
This ticket is locked until we have the design to align the elements of the status column

**Comment by SamantaCasal** [comment]
The statuses are still misaligned, please use the same width


![Image](https://github.com/XLabs/wormscan-ui/assets/69044575/12818fc9-499b-4cab-b42d-eb87485df0f8)

**Comment by SamantaCasal** [comment]
I am going to close this ticket and specifically address this issue in the ticket https://github.com/orgs/XLabs/projects/1/views/1?pane=issue&itemId=31038663
