### ISSUE TITLE
[UI] Fix `ONGOING` icon

### ISSUE THREAD

**Issue by SamantaCasal** [XLabs/wormscan-ui#139]

**Comment by SamantaCasal** [comment]
Fail: The statuses are still misaligned, please use the same width as Figma.
Expected result:

![Image](https://github.com/XLabs/wormscan-ui/assets/69044575/5759f7e7-322c-4cca-bf6c-93520fdd00b0)
![Image](https://github.com/XLabs/wormscan-ui/assets/69044575/2656ad7a-46b8-4690-8fcc-9d93d8d7c174)

Evidence: 


![Image](https://github.com/XLabs/wormscan-ui/assets/69044575/6003cc21-4971-4673-b0de-719e7c5329c4)

**Comment by raop155** [comment]
@Gpluv give us his approve, its ok

**Comment by SamantaCasal** [comment]
QA Opinion: the table statuses should all be the same width, that is, leave the width fixed. It looks untidy as I mentioned before, on desktop and mobile, however, it was approved by design @Gpluv , so I close the ticket.
