### ISSUE TITLE
[TBD] `Fee` amount

### ISSUE THREAD

**Issue by raop155** [XLabs/wormscan-ui#145]
The `fee` amount needs to be defined.
ATM we are displaying what comes from the `payload`

![Image](https://user-images.githubusercontent.com/25652943/243487254-e3f579e1-f350-44cf-8985-a5e481a8aa9d.png)

**Comment by SamantaCasal** [comment]
QA OK! 
It shows as is in the payload, however @erikXLXYZ  how many decimals should have after the dot? 


![Image](https://github.com/XLabs/wormscan-ui/assets/69044575/2b021466-ae58-42a4-b2ae-f73b4ed52190)
