### ISSUE TITLE
[QA] Search by txHash has parsePayload=false set

### ISSUE THREAD

**Issue by SamantaCasal** [XLabs/wormscan-ui#148]
**Environment:**
MacBook Pro, macOS Ventura 13.1.1, Chrome Version 113.0.5672.63.

**Steps**

1. Open Network in the browser
2. Go to https://front.staging.wormscan.io/#/tx/00c7d2504204c6a498f35d5afcd971fdadc1c06348dc093ad6bd21226ae38523
3. In Network click on Header
4. Observe the URL of the API call  https://api.staging.wormscan.io/api/v1/vaas/?txHash=0x00c7d2504204c6a498f35d5afcd971fdadc1c06348dc093ad6bd21226ae38523&parsedPayload=false

**Obtained result:**
The search by txHash is being carried out with parser Payload=false, which implies that it does not bring the payload info, if any.

**Expected result:**
The search by txHash should be done with parse Payload=true, in order to access the payload info, which allows us to identify the destination information, the type of payload, the amount, etc.

**Evidence:**
![Screenshot 2023-06-22 at 9 39 27 PM](https://github.com/XLabs/wormscan-ui/assets/69044575/1e8af451-b123-4ed8-bca1-501bd6005850)

**Comment by raop155** [comment]
@SamantaCasal I disabled this because later I make a request with the `parsePayload===true` but to normalize some behavior I will change how the search bar works.

ref: https://github.com/orgs/XLabs/projects/1/views/1?pane=issue&itemId=31443471

**Comment by SamantaCasal** [comment]
QA OK!
