### ISSUE TITLE
[QA]Link to the tx in the explorer of the Chain 32 (Sei) does not work

### ISSUE THREAD

**Issue by SamantaCasal** [XLabs/wormscan-ui#149]
**Environment:**
MacBook Pro, macOS Ventura 13.1.1, Chrome Version 113.0.5672.63.

**Steps**
1. Go to https://front.staging.wormscan.io/#/tx/17a097521b5da8a64fced9a2bfef7bfe88089b26d0f6e817d58729c4e9e8e308
2. Click on the txHash link
3. Look at the page you are redirecting to

**Obtained result:**
The link leads to https://front.staging.wormscan.io/#/

**Expected result:**
It should lead to the detail of the tx in the Explorer of the Chain

**Evidence:**

https://github.com/XLabs/wormscan-ui/assets/69044575/942c07a8-06bd-44ab-886d-a8c79f81571c

**Comment by raop155** [comment]
@Gpluv can we have Sei logo please? 
Normal logo and Dark logo

**Comment by raop155** [comment]
@SamantaCasal Sei only works on testnet, and also the links for Sei are not quite well handled on the web (still in beta version)
