### ISSUE TITLE
Payload v2

### ISSUE THREAD

**Issue by mliu-xlabs** [XLabs/wormscan-ui#155]
As a wormscan user, I want to be able to send an attestation VAA so that I can verify the pathway to send payloads across blockchains that have not been connected before.

**Acceptance Criteria**

Payload v2 requires Support for attestation VAA. If a duplicate attestation VAA is requested, it will go through anyways, despite the user's misused funds to attest a previously attested asset.
VAA must include a header and a body (message)

For UI requirements:

showing the status of the attestation VAA
showing the attestation as completed
SHowing the attested token together with its name
Link to the token's address
Timestamp of when the attestation was made.

**Additional details on v2**

Header must contain:
- the VAA version
- indicator of what guardian set is signing
- number of signatures stored
- collection of ecdsa signatures

Body must contain:
- The timestamp of the block this message was published in
- The id of the chain that emitted the message
- The contract address (wormhole formatted) that called the core contract
- The auto incrementing integer that represents the number of messages published by this emitter
- The consistency level (finality) required by this emitter
- arbitrary bytes containing the data to be acted on

**Comment by erikXLXYZ** [comment]
For some reason I can no longer edit this ticket. Example of Attestation VAA:

byte        version                
u32         guardian_set_index      
u8          len_signatures           
[][66]byte  signatures 

u32         timestamp       
u32         nonce          
u16         emitter_chain   
[32]byte    emitter_address
u64         sequence     
u8          consistency_level 
[]byte      payload

**Comment by Gpluv** [comment]
Please review the layout of this release for transactions [Payload v2 - Attestation] @mliu-xlabs @erikXLXYZ  (https://www.figma.com/file/kVuUyVjFFcRP55xHxHoKtH/WormholeScan?type=design&node-id=3513-29203&mode=design&t=FapLfP1pkziQtY5o-4)

**Comment by erikXLXYZ** [comment]
looks good to me!

**Comment by SamantaCasal** [comment]
QA Fail: 
The following items are missing: 

- Link to the token's address
- showing the status of the attestation VAA
Tested from iPhone 11+Chrome 

https://github.com/XLabs/wormscan-ui/assets/69044575/610b1356-f1a4-48b5-ad7d-41f45d38cb48

**Comment by SamantaCasal** [comment]
QA OK !


https://github.com/XLabs/wormscan-ui/assets/69044575/7cee5e52-6c07-4cb1-845b-0b19ddf20b6a



https://github.com/XLabs/wormscan-ui/assets/69044575/5e30b02c-d893-42a7-9e29-1d08240e4aa3
