### ISSUE TITLE
[QA]List of Transactions (Tesnet): The link of the tx to the origin explorer is incorrect.

### ISSUE THREAD

**Issue by SamantaCasal** [XLabs/wormscan-ui#160]
**Environment:**
MacBook Pro, macOS Ventura 13.1.1, Chrome Version 113.0.5672.63.
**Prerequisite:** set on TESTNET 

**Steps**
1. https://front.staging.wormscan.io/#/
2. Click on Txs
3. Search for an Avalanche transaction
4. Click on the txHash link 
5. Observe the URL 

**Obtained result:**
The link looks for the transaction made in testnet on the mainnet page

**Expected result:**
The link should redirect to the transaction on the testnet page

**Evidence:**
https://snowtrace.io/tx/0x54652e029600f315a593a2a399651e1320b892f365cf7f017e3fdb201e2c936b
https://testnet.snowtrace.io/tx/0x54652e029600f315a593a2a399651e1320b892f365cf7f017e3fdb201e2c936b

https://github.com/XLabs/wormscan-ui/assets/69044575/b4127f0e-1da5-41ae-8828-16ac82cdc26f

**Comment by raop155** [comment]
You are right, we need to display the testnet explorer pages 🆗

**Comment by SamantaCasal** [comment]
It also happens with ETH https://etherscan.io/tx/0x8c24f9ab0a568a62392d9c6c21a0df8e78342b594c9669c8e9bf3f202e4cc166

With SEI it happens that although it redirects to the testnet page, it still does not find the transaction

**Comment by SamantaCasal** [comment]
Tested for: 
✅ Avalanche
✅ Ethereum
✅ Polygon
✅ Celo
✅ Moonbeam 
✅ Fantom
✅ BSC

Otras: 
✅ Solana -> DEVNET 
✅ Algorand -> Testnet
