### ISSUE TITLE
[UI] Verify tx / address come with the right encode/decode format (evm, solana, sui, etc)

### ISSUE THREAD

**Issue by SamantaCasal** [XLabs/wormscan-ui#165]
This has to be fixed in the back-end side

--

Waiting for: https://xlabs-org.slack.com/archives/C04LXNYQU14/p1687362726236819?thread_ts=1687290691.714349&cid=C04LXNYQU14

**Comment by SamantaCasal** [comment]
@raop155 What should be tested in this ticket?

**Comment by raop155** [comment]
@SamantaCasal This should test all tx hashes/addresses are coming with the right format.
This is something WIP from the back-end team

**Comment by SamantaCasal** [comment]
@raop155 Okay great. Just one more question, what would be the correct format?

**Comment by raop155** [comment]
@SamantaCasal I am really sure 100%
But the "green test" will be the all external links to the explorer works ok :) 
@agodnic knows more about the tech detail, but is something like

EVM = hex
Solana= = base58? (not 100% sure)

**Comment by agodnic** [comment]
This will be partially addressed in https://github.com/wormhole-foundation/wormhole-explorer/issues/512#issuecomment-1623778801

Context: https://xlabs-org.slack.com/archives/C04LXNYQU14/p1688652053280519

**Comment by SamantaCasal** [comment]
OK!
