### ISSUE TITLE
[QA] Txs List: The txHash are shown with different lengths

### ISSUE THREAD

**Issue by SamantaCasal** [XLabs/wormscan-ui#174]
**Environment:**
MacBook Pro, macOS Ventura 13.1.1, Chrome Version 113.0.5672.63.

**Steps**

1. Go to https://front.staging.wormscan.io/#/
2. Click on Txs
3. Observe the length of the txHash

**Obtained result:**
The txHash has different lengths, however, they are all abbreviated.

**Expected result:**
They should be the same length and be aligned

**Evidence**

![Image](https://github.com/XLabs/wormscan-ui/assets/69044575/a6b9b680-9c49-4b30-a522-fbeafb335297)

**Comment by raop155** [comment]
@SamantaCasal What we can do to achieve this is to make all addresses UPPERCASE.

But to make this constant/normalized we should do in all addresses, tx list and tx detail pages?

@Gpluv what do you think?

**Comment by Gpluv** [comment]
@raop155 
1. Try leaving everything in uppercase. If that works, you should also change the format on the page: TX Detail.
2. If point 1 doesn't work, leave the icon fixed regardless of the size of the address characters, all aligned to 16px or 24px from the address box.

@SamantaCasal

**Comment by SamantaCasal** [comment]
QA OK! 


![Image](https://github.com/XLabs/wormscan-ui/assets/69044575/a26d4bff-d751-47bf-8c8a-65c758c8b580)
