### ISSUE TITLE
Disclaimer for transactions with receiver address not fetchable

### ISSUE THREAD

**Issue by mliu-xlabs** [XLabs/wormscan-ui#181]
When a transaction has a receiver address that is not viewable in the back end, the smart contract will be shown in the UI as the receiver with the following disclaimer:

Address shown corresponds to Smart Contract handling the transaction. Funds will be received in your reciver address nonetheless.

----------------------------------------------------

Please review the icon design and tooltip so that Ricardo can proceed:
https://www.figma.com/file/kVuUyVjFFcRP55xHxHoKtH/WormholeScan?type=design&node-id=3432%3A29397&mode=design&t=uGBJsPUeqW9bAEUT-1

Erik approves this.

Design approved by George:

![Image](https://user-images.githubusercontent.com/25652943/251818363-1f82b1f0-2535-4a5a-ba36-52eac9eb8013.png)

Waiting for back-end new endpoints

**Comment by mliu-xlabs** [comment]
@erikXLXYZ lets update the text to this:

Address shown corresponds to a Smart Contract handling the transaction. Funds will be sent to your receiver address.

**Comment by mliu-xlabs** [comment]
is this a duplicate of https://github.com/orgs/XLabs/projects/1/views/2?pane=issue&itemId=31321981

**Comment by raop155** [comment]
@mliu-xlabs yes, it is.

**Comment by SamantaCasal** [comment]
Functionality QA OK, however on mobile is one style bug that will be reported in another ticket. 

![Image](https://github.com/XLabs/wormscan-ui/assets/69044575/f05d2502-e810-4d74-a55f-d92e158ddb5d)



![Image](https://github.com/XLabs/wormscan-ui/assets/69044575/f4025387-f8db-4993-afba-8c8a7fabcbd4)
