### ISSUE TITLE
[QA] The destination wallet link doesn't work correctly

### ISSUE THREAD

**Issue by SamantaCasal** [XLabs/wormscan-ui#184]
**Environment:**
MacBook Pro, macOS Ventura 13.1.1, Chrome Version 113.0.5672.63.

**Tested from:** https://front.staging.wormscan.io/#/ on Mainnet and testnet

**Steps** 

1. Go to https://front.staging.wormscan.io/#/
2. Click on txs
3. Select one transaction of the list that has TO address
4. Click on the destination wallet link

**Obtained result:**
When you click on Destination wallet link, you go to the wormholescan home page

**Expected result:**
The link should redirect to the destination wallet detail

**Evidence:**
https://github.com/XLabs/wormscan-ui/assets/69044575/a1a6e647-7419-4307-90a1-3a9e553fa316

**Comment by raop155** [comment]
Hi Sami, I will pass this to block, we still are waiting for the new API deployment:

https://github.com/wormhole-foundation/wormhole-explorer/pull/520

After this I will tackle all the Qa related :)

**Comment by SamantaCasal** [comment]
QA OK! 

https://github.com/XLabs/wormscan-ui/assets/69044575/1b024793-3016-464f-b3ac-3059e98c440b
