### ISSUE TITLE
[QA] Address detail: It does not show the list of transactions

### ISSUE THREAD

**Issue by SamantaCasal** [XLabs/wormscan-ui#191]
**Environment:**
MacBook Pro, macOS Ventura 13.1.1, Chrome Version 113.0.5672.63.

**Tested from:** https://front.staging.wormscan.io/#/ on Mainnet and testnet

**Steps**

1. Go to 
2. Copy and paste this address 0xa43698df7321d6ce5a642bae75d2f08cad543964
3. Observe the transactions list
4. Await a few seconds
5. Observe the message in the transactions list 
6. Repeat step 2 but with the same address in another format 0x000000000000000000000000a43698df7321d6ce5a642bae75d2f08cad543964
7. Repeat step 4 to 5 

**Obtained result:**

- First, show the list of transactions
- Then it shows the message "no txs found"
- When looking for the address again, it continues to show the same message, however, the address carried out transactions (https://bscscan.com/tx/0x9b3d57357fff3d944a86ab518a86d73949d0a6dc89fc29427ed474f51c7b69da)

**Expected result:**
It should show the list of transactions.
**Note:** although this bug happened to me with this address, it does not mean that it does not happen with other addresses. The specific case was shown to better explain the issue.

**Evidence:**

https://github.com/XLabs/wormscan-ui/assets/69044575/6d6e800c-73de-4646-a302-17ce60279e64

**Comment by raop155** [comment]
@agodnic Looks like it is a back-end issue as I mentioned to Agus, he is going review the issue,

FYI @SamantaCasal

**Comment by SamantaCasal** [comment]
QA OK!

**Comment by SamantaCasal** [comment]
![Image](https://github.com/XLabs/wormscan-ui/assets/69044575/fe8c3d5f-82d8-495c-a36e-8f32ee9511a5)
