### ISSUE TITLE
[UI] Tx Detail Signed Guardians Graph full feature

### ISSUE THREAD

**Issue by SamantaCasal** [XLabs/wormscan-ui#194]
Figma ref: https://www.figma.com/file/kVuUyVjFFcRP55xHxHoKtH/WormScan?type=design&node-id=2367-23403&t=oQwNclCIy5IYSRiA-0

**Comment by SamantaCasal** [comment]
❗ When you click on the copy button on mobile, the tooltip doesn't see.
Tested from: iPhone 13 proMax+Brave  and iPhone 11 pro+ Chrome. 
 FYI: @valentinoConti 

https://github.com/XLabs/wormscan-ui/assets/69044575/49f715d1-916d-4914-a557-621116ac6165

**Comment by SamantaCasal** [comment]
This issue still happens. 
FYI: @valentinoConti 

https://github.com/XLabs/wormscan-ui/assets/69044575/9e9cfdd0-d82c-42b8-8d67-917ab530c9bd

**Comment by valentinoConti** [comment]
"La tercera es la vencida"

Ready to test again, worked now for me on i14 ProMax on Safari, Chrome and Brave 🙌🏼

**Comment by SamantaCasal** [comment]
QA OK! 

https://github.com/XLabs/wormscan-ui/assets/69044575/e52cc26d-114f-4256-82ab-1313ce54b43d
