### ISSUE TITLE
[QA] Mobile: Visual bug in the footer

### ISSUE THREAD

**Issue by SamantaCasal** [XLabs/wormscan-ui#207]
_Tested from:_  Iphone 11. iOS version 16.5
Chrome+Safari+Brave

**Steps**

1. Go to www.wormholescan.io
2. Scroll down until the footer
3. Observe the background

**Obtained result:**
The background shows the wormhole rings 

**Expected result:**
The background should be the full selected color, without the rings.

**Evidence:**

![Image](https://github.com/XLabs/wormscan-ui/assets/69044575/e2fce500-304c-4d61-ab5a-816084b8f1ab)

**Comment by raop155** [comment]
@Gpluv 

Can you share the mobile background without the rings, please?
(The same issue we had with the desktop bg 😁 )

fyi: @SamantaCasal

**Comment by SamantaCasal** [comment]
QA OK! 


![Image](https://github.com/XLabs/wormscan-ui/assets/69044575/b8b8a0bf-e2fc-4099-8b4b-25271463aadf)
