### ISSUE TITLE
[QA] [Mobile-Testnet] Transaction detail: The circle of signatures looks incomplete

### ISSUE THREAD

**Issue by SamantaCasal** [XLabs/wormscan-ui#217]
**Environment:**
- iPhone 11. iOs 16.5+Chroem
- Pixel 5 (393x851px) Chrome (dev tool) 

**Tested from:** https://wormholescan.io/#/?network=testnet

**Steps**
1. Go https://wormholescan.io/#/?network=testnet
2. Go to txs
3. Click over one transaction
4. Observe the circle in the row "signed vaa"

**Obtained result:**
The circle of signatures looks incomplete 

**Expected result:**
Since there is only one signature, the circle should be closed. @Gpluv , could you confirm if this is expected?

**Evidence:**

![Image](https://github.com/XLabs/wormscan-ui/assets/69044575/2d92f564-980b-44c1-9858-0430928592d5)

**Comment by Gpluv** [comment]
Yes please, let the circle close. @raop155

**Comment by SamantaCasal** [comment]
QA OK!
