### ISSUE TITLE
[Tx list enhancement] Pagination

### ISSUE THREAD

**Issue by SamantaCasal** [XLabs/wormscan-ui#239]
As an explorer user, I want to be able to navigate the live list through various pages and select specific pages so that I can navigate through the interface with more precision

Acceptance criteria

- Tx list view must add page selection
- Page selection must include FIrst, last, next, previous
- Specific buttons for page 1,2,3,4,5

---

@erikXLXYZ

This functionality cannot be done now, we currently do not know about the limit of the total pages we have when searching all txs or searching txs by some filter.

So this will need work on:
- UI 
  - How to display 1,2,3,4,5 pages <<|<| 1, 2, 3, 4, 5 |>|>> + current page 

- Back-end
- Front-end

FYI: @gipsh @Gpluv

**Comment by Gpluv** [comment]
Talk with Ricardo and Chipi

**Comment by SamantaCasal** [comment]
QA OK!
