### ISSUE TITLE
[QA] Sankey chart: Message does not reflect what the chart shows

### ISSUE THREAD

**Issue by SamantaCasal** [XLabs/wormscan-ui#248]
**Environment:**
MacBook Pro, macOS Ventura 13.1.1, Chrome Version 113.0.5672.63.

**Tested from:** https://wormholescan.io/#/

**Steps**
1. Go https://wormholescan.io/#
2. Go to the Sankey chart
3. Observe the message in the lower right margin

**Obtained result:**
The message says "Chart shows only top ten destinations / assets" however, it shows the list of all transactions between blockchains and their participation in volume / transactions

**Expected result:**
@Gpluv Could you help us with this definition?
The legend should either be removed or modified in such a way that it reflects what we currently show on the chart.

**Evidence:**

![Image](https://github.com/XLabs/wormscan-ui/assets/69044575/c53f763c-5d90-4855-882a-02c5c8de67fa)

**Comment by valentinoConti** [comment]
Are we sure that this is wrong?? We are showing every **source** chain info but for every of those the chart is indeed showing only top ten destinations/assets 🤔

**Comment by SamantaCasal** [comment]
mm no, I think it was my mistake, now I see that when saying destinations/assets and being under the destination column, the message is correct. I will deprecate the ticket. 
FYI: @valentinoConti @Gpluv
