### ISSUE TITLE
[BUG] Token links redirect to pages that show a 404 error or to the explorer home page

### ISSUE THREAD

**Issue by SamantaCasal** [XLabs/wormscan-ui#337]
**Environment:** macOs ventura 13.5.2.  Chrome Version 117.0.5938.92 (Official Build) (arm64)

**Tested from:**
[STG](https://xlabs.github.io/wormscan-ui/#/)
[PROD](https://wormholescan.io/#/)

**Current behavior:**
On the transaction detail page, the token link sometimes redirects to a page that gives 404 and other times to the explorer home page

**Expected behavior:**
1. In cases where the page is available, it should redirect to the token page of the chain where the token was created.

2. In cases where the page is not available, what is the expected behavior? @erikXLXYZ @Gpluv 

**Steps to reproduce**
1. Go to https://wormholescan.io/#/tx/9df3eb697ec865bc7a02a3e27f38dee8957c710562dc0e8fea58d45c58abd0f0
2.  Click on UST
3. Observe the page 
4. Go to https://xlabs.github.io/wormscan-ui/#/tx/7d4963fe9a658568cdd4ba90bc20fdb2197be99fefed1c9664906b0442d76b4e
5. Click on USDT 
6. Observe 
**Evidence:**

404: 

https://github.com/wormhole-foundation/wormhole-explorer/assets/69044575/8f06154c-d8b5-4073-b4fa-9a773c52c76d

Home Page: 

https://github.com/wormhole-foundation/wormhole-explorer/assets/69044575/9b69e071-9ded-491e-b5b2-ab977d85bcd3

**Comment by erikXLXYZ** [comment]
Is it possible to know in the back end if the link will result in a 404? If so, the link to those pages should be removed. Otherwise, redirect to Whscan homepage,

**Comment by Gpluv** [comment]
We reviewed it with Giuliano, it is best not to show a link when we know that the result will be that error.
The interface will then show the section without a link, just as normal text.

**Comment by giulianoconti** [comment]
@erikXLXYZ 
For now, we only fixed the issue for the few cases where we don't receive the necessary information from the backend to display the link. Therefore, it won't appear as a link but simply as text.

For the cases where we do have the information to show the link, but it directs us to a 404 error page, I'm not sure if there's a way to know it will be a 404 and not display the link.

**Comment by giulianoconti** [comment]
@SamantaCasal 

I fixed the problem with the [token links](https://xlabs.github.io/wormscan-ui/#/tx/7d4963fe9a658568cdd4ba90bc20fdb2197be99fefed1c9664906b0442d76b4e) that were taking us to the home page.

For the token links that send us to an error page like 404, I think we can't fix that from the front end.

**Comment by SamantaCasal** [comment]
Tested from: https://wormholescan.io/#/tx/8c3293a4db8c94b4ad5e436bc8dc85ab7c6688350666c80c4ece40f200cf6b1a?network=TESTNET


![Image](https://github.com/XLabs/wormscan-ui/assets/69044575/3a80e1c7-07ad-494b-a092-197547ffffe7)

https://xlabs.github.io/wormscan-ui/#/tx/7d4963fe9a658568cdd4ba90bc20fdb2197be99fefed1c9664906b0442d76b4e


![Image](https://github.com/XLabs/wormscan-ui/assets/69044575/5825b52d-9252-41e1-b523-aaa79fde3e69)

**Comment by SamantaCasal** [comment]
In prod. v1.1.2
