### ISSUE TITLE
parse payload and show it on raw data for txs without info

### ISSUE THREAD

**Issue by valentinoConti** [XLabs/wormscan-ui#350]
For transactions where we don't know how to read the payload, we still have to show at least the raw payload so the user (or dev) that sent that transaction with a specific payload, can see on the explorer if the transaction sent the information correctly.

After this ticket gets implemented, every transaction should show a 'payload' inside the "signed vaa" section on the "raw data" section of a transaction detail.

**Comment by valentinoConti** [comment]
Done!

**example**:

PROD (not implemented):
https://wormholescan.io/#/tx/dYzJceoehbAaf7XkaAPyM6DeAQhxHyiewZHXEzUDgDh?view=rawdata

DEV (implemented):
https://xlabs.github.io/wormscan-ui/#/tx/dYzJceoehbAaf7XkaAPyM6DeAQhxHyiewZHXEzUDgDh?view=rawdata

**Comment by SamantaCasal** [comment]
QA OK!

**Comment by SamantaCasal** [comment]
In prod v1.1.2
