### ISSUE TITLE
Change designs

### ISSUE THREAD

**Issue by giulianoconti** [XLabs/wormscan-ui#389]
https://wormholescan.io/#/

![Image](https://github.com/XLabs/wormscan-ui/assets/88043910/b67843cc-0220-4e4a-bf3d-cd3c2e2028d9)
![Image](https://github.com/XLabs/wormscan-ui/assets/88043910/e1328ce9-52c8-47b7-bfdd-e50b5d958830)

Figma

![Image](https://github.com/XLabs/wormscan-ui/assets/88043910/6b5dfff9-c128-405c-8ba1-02c140252a18)
![Image](https://github.com/XLabs/wormscan-ui/assets/88043910/0b606999-1366-4376-a481-c0a37b47eec2)

**Comment by SamantaCasal** [comment]
Replace this ticket for: 
https://github.com/orgs/XLabs/projects/1/views/7?pane=issue&itemId=41972464
 https://github.com/orgs/XLabs/projects/1/views/2?pane=issue&itemId=43349973
 https://github.com/orgs/XLabs/projects/1/views/7?pane=issue&itemId=43281961
