### ISSUE TITLE
Apply `Resume Transaction` button for Connect & WH Gateway txs

### ISSUE THREAD

**Issue by SamantaCasal** [XLabs/wormscan-ui#505]
### Description 
Currently, for those transactions on the Portal Bridge where we are unable to retrieve information about the Redeem, either due to it being on an unsupported target chain or the transaction type being unsupported, we offer users the option to proceed with their transaction by redirecting them to the advanced-tools page of the Portal Bridge. 
This ticket aims to implement the same mechanism for transactions conducted through the `Portal Bridge-Connect,` and `Portal Bridge-WH Gateway`. 

![Image](https://github.com/XLabs/wormscan-ui/assets/69044575/b6948a3c-1b8b-4933-b868-c27d64772f3f)

### Acceptance Criteria

1. It should redirect to the RESUME TRANSACTION section of  Connect. 

![Image](https://github.com/XLabs/wormscan-ui/assets/69044575/3e8790aa-fc3c-469e-8603-b5d23045d2c4)

2. Redirect users to the Portal Bridge/resume transaction page with the original txHash and the source chain pre-filled.

Note: The Portal team (Sebastian) should be asked to help us implement the deep link to this page.

**Comment by giulianoconti** [comment]
Blocked until we have the deep linking fix in portalbridge

**Comment by SamantaCasal** [comment]
Preview version: https://preview.portalbridge.com/caab316c7d/

**Comment by giulianoconti** [comment]
Tested with the preview version 👍
Blocked until we have the deep linking fix in portalbridge prod
(we need just change the url)

**Comment by SamantaCasal** [comment]
Wh Gateway: https://xlabs.github.io/wormscan-ui/#/tx/4wDMxGy4XmHwbPAhYguuxvPZuEtxi1obm3CEK7rdxL7bLkjwe3SYhKqfcooDz9sLqJSY1QcdNTmw795D1q4SUxCn



![Image](https://github.com/XLabs/wormscan-ui/assets/69044575/594a7dc4-3dab-4f11-9ede-655bbd02e7b5)
