### ISSUE TITLE
[Bug]-Scrolling causes gap between body and footer on page

### ISSUE THREAD

**Issue by SamantaCasal** [XLabs/wormscan-ui#61]
**Environment:** https://front.staging.wormscan.io/#/
**S.O:** iOs+Chrome 

**Steps**
1. Go to https://front.staging.wormscan.io/#/
2. Scroll down
3. Observe

**Obtained result:** When you scroll down the page, there is a blank space between the body and the footer.
**Evidence:** 

https://user-images.githubusercontent.com/69044575/236000523-d543ba3d-8961-4d7f-ab8e-98828671ee7c.MP4

**Comment by raop155** [comment]
Looks like this is a performance issue with some components as first sight.
I will need to investigate more.

**Comment by SamantaCasal** [comment]
QA ok! 
Evidence: 


https://github.com/XLabs/wormscan-ui/assets/69044575/c621bde6-857f-4b54-8c27-d7a3b0c28f9e
