### ISSUE TITLE
Search results page

### ISSUE THREAD

**Issue by hernandiegosavio** [XLabs/wormscan-ui#71]
When search by address it must show the list of transactions.

**Comment by raop155** [comment]
This is related to this:
https://github.com/orgs/XLabs/projects/1/views/1?pane=issue&itemId=27271408 (WIP)

**Comment by raop155** [comment]
Waiting for new endpoint: https://github.com/wormhole-foundation/wormhole-explorer/issues/385

**Comment by raop155** [comment]
The current endpoint does not support origin address (source wallet)

**Comment by SamantaCasal** [comment]
QA OK!
