### ISSUE TITLE
[QA] Various visual and UX bugs on mobile

### ISSUE THREAD

**Issue by SamantaCasal** [XLabs/wormscan-ui#74]
**Environment:**

- IPhone 11, iOS 16.0(20A362), Chrome. 
- https://front.staging.wormscan.io/#/

**Prerequisites:** 
Set the browser dev tool to mobile or have a mobile phone.

**Steps:**
1. Go to https://front.staging.wormscan.io/#/
2. Click on the search input 
3. Write anything
4. Click on the search icon
5. Observe the sidebar menu
6. Scroll down 
7. Observe the scorecards values 
8. Keep scrolling down
9. Observe the page size

**Obtained result:**

1. The sidebar opens after clicking the search icon and remains open
2. The elements of the scorecards are outside the card.
3. The page is seen in another size, narrower.
4. When uploading, it shows white space before rendering the info.

**Expected result:**

1. The sidebar shouldn't open
2. Scorecard items should always be visible inside the box container.
3. The page should be displayed in the full width of the device
4. When you scroll up you should see the info that you already rendered previously.

**Evidence:** 

https://github.com/XLabs/wormscan-ui/assets/69044575/a3eadb79-f5b3-4083-8697-b6233119c354

**Comment by raop155** [comment]
@SamantaCasal Cannot reproduce the "opened" sidebar, tried in mobile android, and safari mobile view.
 hmmm. I still can't do a repro I will push my fixes and let to you to test it.

p4 -> as I mentioned in other task, looks like it is something with re-render or performance. Will take a look also.

**Comment by SamantaCasal** [comment]
QA ok! 
Evidence: 


https://github.com/XLabs/wormscan-ui/assets/69044575/c3cf28b1-1f88-4bcc-8f62-470b8fff2158
