### ISSUE TITLE
[QA] Transaction History Graph: Dates overlap on mobile.

### ISSUE THREAD

**Issue by SamantaCasal** [XLabs/wormscan-ui#78]
**Environment:**

- IPhone 11, iOS 16.0(20A362), Chrome.
- Pixel 5. (with Chrome dev tools) 
- https://front.staging.wormscan.io/#/

**Prerequisites:**
Set the browser dev tool to mobile or have a mobile phone.

**Steps:**

1. Go to https://front.staging.wormscan.io/#/
2. Click on 1M on the Transaction History graph
3. Observe the DATE on the x-axis.

**Obtained result:**
Dates in the last few weeks overlap

**Expected result:** 
The dates are clearly visible 

**Evidence:** 
![IMG_91E7B9413FE2-1](https://github.com/XLabs/wormscan-ui/assets/69044575/d7f52f9f-81e0-4e6e-b988-a19eb56af3d9)
![Screenshot 2023-05-23 at 11 09 25 PM](https://github.com/XLabs/wormscan-ui/assets/69044575/d8b6297d-206a-464b-88b6-72b25374c0b7)

**Comment by raop155** [comment]
@SamantaCasal Please test it again :)

**Comment by SamantaCasal** [comment]
QA OK! 
Evidence: 
![Screenshot 2023-05-24 at 4 39 35 PM](https://github.com/XLabs/wormscan-ui/assets/69044575/8b69ced6-36f1-46f9-8d5a-fc54637b65bb)
