### ISSUE TITLE
[QA] The transaction history graph shows the current data twice when filtered by 1W

### ISSUE THREAD

**Issue by SamantaCasal** [XLabs/wormscan-ui#82]
**Environment:**
MacBook Pro, macOS Ventura 13.1.1, Chrome Version 113.0.5672.63.
https://front.staging.wormscan.io/#/

**Steps**

1. Go to the Home Page https://front.staging.wormscan.io/#/
2. In the transaction history graph
3.  Click on 1W
4. Observe on the X axis the last day

**Obtained result:** 
Show today (Tuesday) twice
**Note:** I think that the endpoint brings the information from yesterday until 00:00 today, that would be the complete data from yesterday. Today accumulates in the first element of the array. https://api.staging.wormscan.io/api/v1/last-txs?timeSpan=1w&sampleRate=1d

**Expected result:**
The graph should show the information for the last 7 days, that is, it should show 7 days. For example, from Wednesday 05/24 to Tuesday 05/30 (whatever has accumulated until the last update). 
![Screenshot 2023-05-30 at 5 07 27 PM](https://github.com/XLabs/wormscan-ui/assets/69044575/ae136c00-345e-4fcb-9eb9-193af42bcbe3)

**Example of the distribution of the week:**

![Screenshot 2023-05-30 at 4 47 35 PM](https://github.com/XLabs/wormscan-ui/assets/69044575/2a4bff7f-d9ec-4a28-9fe1-2d7694677bd9)

**Evidence:**

![Screenshot 2023-05-30 at 4 45 05 PM](https://github.com/XLabs/wormscan-ui/assets/69044575/9a0be111-0ebc-497c-8e68-933d40a07075)

**Comment by raop155** [comment]
@SamantaCasal @gipsh 
I think this will be resolved on the back-end side :)

**Comment by mliu-xlabs** [comment]
I have recreated it on backend project:
https://github.com/orgs/wormhole-foundation/projects/1/views/8?pane=issue&itemId=30794504
