### ISSUE TITLE
[QA] Other is missing from the Chains list of the sankey chart

### ISSUE THREAD

**Issue by SamantaCasal** [XLabs/wormscan-ui#89]
**Environment:**
MacBook Pro, macOS Ventura 13.1.1, Chrome Version 113.0.5672.63.

**Steps**

1. Go to https://front.staging.wormscan.io/#/
2. Go to sankey chart 
3. Observe the last Chains on the source list

**Obtained result:**
A list of 10 Chains is displayed.

**Expected result:**
The 10th place in the Chains list should show Other, as designed in https://www.figma.com/file/kVuUyVjFFcRP55xHxHoKtH/WormScan?type=design&node-id=2335-22616&t=TF9OCe8NPp58gmW2-0

**Evidence:** 

![Image](https://github.com/XLabs/wormscan-ui/assets/69044575/d73bff16-b89d-4a15-8d76-b91d5a979986)

**Comment by raop155** [comment]
@valentinoConti I am assigning this to you because is related to the other task to implement the `endpoint` into this section. thanks 🙏 

FYI: @SamantaCasal @hernandiegosavio

**Comment by SamantaCasal** [comment]
QA OK!
