### ISSUE TITLE
[QA] Missing wormhole background in Join Us section

### ISSUE THREAD

**Issue by SamantaCasal** [XLabs/wormscan-ui#93]
**Environment:**
MacBook Pro, macOS Ventura 13.1.1, Chrome Version 113.0.5672.63.

**Steps**

1. Go to https://front.staging.wormscan.io/#/
2. Scroll down to Join Us
3. Observe the background

**Obtained result:**
The wormhole background is not applied

**Expected result:**
It should be visible against the wormhole background, as shown in
https://www.figma.com/file/kVuUyVjFFcRP55xHxHoKtH/WormScan?type=design&node-id=2335-22616&t=W9UlXFvsFPGagyFY-0

![Image](https://github.com/XLabs/wormscan-ui/assets/69044575/5ab9345e-70ea-4a92-b6aa-fc89635e9b33)

**Evidence:**

![Image](https://github.com/XLabs/wormscan-ui/assets/69044575/e270353a-e2a2-4175-bfd8-7b3eae3e6357)

**Comment by raop155** [comment]
@SamantaCasal 
This can depend on the `viewport` because this "thingy" is on the `background-image`, so it is not in a fixed position.

I'm pretty sure that George knows about it. hmmm. 🤔 

![Image](https://github.com/XLabs/wormscan-ui/assets/25652943/ee0d99ac-c754-439d-b704-794b6b3040f9)

**Comment by SamantaCasal** [comment]
ok!

**Comment by SamantaCasal** [comment]
QA ok!


![Image](https://github.com/XLabs/wormscan-ui/assets/69044575/446e446b-b08b-4c39-8c7a-cdc6ced95bf5)
